Grammar fixes, Possible phrasing improvements, More interesting death…
Tau-ri-Dev/Mod-JSG-1.12.2 pull request #310
Opened 2023-11-27 20:10 UTC by VirgilCore

… messages

There's a lot of changes in here so it's up to you which ones you accept and which ones you dont.

2023-11-27 20:51 UTC, MineDragonCZ requested changes
Some things should be changed

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +advancement.zpm_slot.title=Oh yeah.
Looks bad with the dot at the end...

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +advancement.beamer.title=Wireless Resource Transport
Beamers gonna beam is refenrece to Gaters gonna gate

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.gear_naquadah.name=Naquadah Gear
Shoud stay as it is... Its naming convence of JSG

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.plate_naquadah.name=Naquadah Plate
Shoud stay as it is... Its naming convence of JSG

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.schematic_ancient.name=Ancient Transport Rings Schematic
Shoud stay as it is... Its naming convence of JSG

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.invisible_block.name=Invisible Block
Well... Can be as it was... Its internal thing

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +prop.jsg.platform_ships_block.name=Ring Cover (Ship)
Its a block... So platform as a whole thing

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.zpm_slot_block.name=ZPM Slot
Shoud stay as it is... Its naming convence of JSG

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_controller_block.not_linked=Controller is not linked
Shoud stay as it is... Its naming convence of JSG

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_ancient_block.name=Ancient Transport Rings
Shoud stay as it is... Its naming convence of JSG

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +gui.beamer.beamer_ok=Beamer in range
Its not about range... The beamer should actually facing the gate (so see it)

2023-11-27 20:51 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +jsg.subtitle.beamer_loop=Beamer transmits
It can also recieve (so better as it is)

2023-11-27 23:04 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +advancement.beamer.title=Wireless Resource Transport
Okay, but the only time i've ever seen the phrase "gater's gonna gate"  was on a single gif on tenor and nowhere else.

2023-11-27 23:05 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.gear_naquadah.name=Naquadah Gear
The grammar is better and it is more aligned with standard naming conventions for minecraft items.

2023-11-27 23:05 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.plate_naquadah.name=Naquadah Plate
The grammar is better and it is more aligned with standard naming conventions for minecraft items.

2023-11-27 23:05 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.schematic_ancient.name=Ancient Transport Rings Schematic
The grammar is better and it is more aligned with standard naming conventions for minecraft items.

2023-11-27 23:05 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.zpm_slot_block.name=ZPM Slot
The grammar is better and it is more aligned with standard naming conventions for minecraft items.

2023-11-27 23:06 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_controller_block.not_linked=Controller is not linked
The grammar is better and it is more aligned with standard naming conventions for minecraft items.

2023-11-27 23:06 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_ancient_block.name=Ancient Transport Rings
The grammar is better and it is more aligned with standard naming conventions for minecraft items.

2023-11-27 23:06 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +advancement.zpm_slot.title=Oh yeah.
I thought it looked better, it makes the tone more like satisfaction

2023-11-27 23:07 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.invisible_block.name=Invisible Block
It shows up with mods like WAILA and HWYLA. Renaming it makes it a little less silly when you see it pop up with those mods. I've had many people comment on the name as being silly.

2023-11-27 23:09 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +prop.jsg.platform_ships_block.name=Ring Cover (Ship)
This is for the hatch model that goes over the rings, right? If so then its pretty accurate, it adds a cover over the rings.

2023-11-28 20:13 UTC, MR-Spagetty commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.gear_naquadah.name=Naquadah Gear
_Do you correct people's names when there is a perceived grammatical mistake in them?_

2023-11-28 20:32 UTC, MR-Spagetty commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_controller_block.not_linked=Controller is not linked
also singular of transport rings is transport rings

2023-11-28 21:13 UTC, VirgilCore commented
I was organising my clone of the repo and didnt mean to delete this. Apparently renaming the branch closes the pull request.

2023-11-28 21:18 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.gear_naquadah.name=Naquadah Gear
> _Do you correct people's names when there is a perceived grammatical mistake in them?_

This is not a matter of people's names but rather how an object is meant to be addressed in the english language. Adjective goes before the Noun, not after.

2023-11-28 21:21 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_controller_block.not_linked=Controller is not linked
The phrase reads better when Ring is written as singular

2023-11-29 18:39 UTC, MineDragonCZ commented
The namings are still wrong... Should be "Stargate Base Block (Milky Way)" for example

2023-11-29 18:40 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +config.jsg.zpm.tooltip=Configuration of ZPMs and ZPM Hubs
Its only 1 ZPM type in mod not more ZPM types so why that ZPM**s**

2023-11-29 18:45 UTC, MineDragonCZ requested changes

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.naquadah_ore_stone.name=Naquadah Ore
Should be as it is... Its a variant of the ore...

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +prop.jsg.platform_ships_block.name=Ship Ring Platform
Same as with blocks... Naming of things is wrong

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.dhd_block.name=Milky Way Dial Home Device
Same as with blocks... Naming of things is wrong

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.dhd_pegasus_block.name=Pegasus Dial Home Device
Same as MW dhd

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_milkyway_chevron_block.name=Milky Way Stargate Chevron
Wrong naming...

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_orlin_member_block.name=Orlin's Stargate Ring
Wrong naming...

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_universe_ring_block.name=Universe Stargate Ring
Wrong naming...

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_pegasus_chevron_block.name=Pegasus Stargate Chevron
Wrong naming...

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.capacitor_block_empty.name=Empty Capacitor Bank
Wrong naming...

2023-11-29 18:45 UTC, MineDragonCZ commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_controller_block.not_linked=Controller is not linked
They are Transport Rings, not ring... There are more rings coming from the floor/ceiling...
Also wrong naming...

2023-11-29 18:46 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.universe_dialer.broken.name=Broken Universe Dialer
You can´t obtain it anymore... Its also status of Dialer

2023-11-29 18:49 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> -tile.jsg.invisible_block.name=You can't see me block
We want You can't see me block - its our tradition from times when MRJake started Aunis! **You must LIVE WITH THAT. DOT!**

2023-11-29 18:50 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +prop.jsg.decor_abydos_lamp_on_block.name=Abydos Brazier (On)
Approved

2023-11-29 18:53 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> -tile.jsg.dhd_block.name=Dial Home Device (Milky Way DHD)
Our original naming contains all information for searching in JEI - dial home device - milky way MW and DHD.

**YOUR TRANSLATION NOT! SO DENIED!**

2023-11-29 18:54 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> -tile.jsg.dhd_pegasus_block.name=Dial Home Device (Pegasus DHD)
Our original naming contains all information for searching in JEI - dial home device - pegasus and DHD.

**YOUR TRANSLATION NOT! SO DENIED!**

2023-11-29 18:57 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_orlin_base_block.name=Orlin's Stargate Base
Same with ´ nobody except english speaking dudes cant write right symbol for that...

So IF anybody try to search with that for orlins gate JEI will find nothing due fk **'** BECAUSE ANYBODY CANT FIGURE OUT WHY JEI CANT FOUND IT!!!

WELL DONE VIRGIL

2023-11-29 18:57 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
SAME HERE

2023-11-29 18:58 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.creative_zpm.name=Creative Zero Point Module (ZPM)
Really?

2023-11-29 18:59 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +death.attack.wrongSide=%s entered the wrong side of the gate
Hmmm our perfect gate didnt notice gate... where Star? :D

2023-11-29 19:00 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +jsg.subtitle.iris_hit=Thud against the iris
Something hit iris is more known phrase

2023-11-29 19:01 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +jsg.subtitle.shield_hit=Thud against the shield
Something hit shield is more known phrase

2023-11-29 19:10 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +config.jsg.zpm.tooltip=Configuration of ZPMs and ZPM Hubs
"ZPMs" is grammatically correct, just as "Stargates Config" is correct. There is more than one ZPM in any given world, just as there are Stargates or Transport Rings, etc.

2023-11-29 19:11 UTC, Fredyman95 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.gear_naquadah.name=Naquadah Gear
Well you are even changing thing that are named because of searching function and make it different from other mods e.g thermal expansion if you have 2 gear that look tottaly similiar you can say this one is from JSG by name... and you are saying **D**uck people **D**uck searching. Those things arent wrong, people understand it.  Lets change brain with dictionary and make people more angry that they cant find anything due stupid symbols as ´. But You and your dictionary will be happy. 

Also you are changing things that are here tradition from core mod time - AUNIS. When MRJake code it. So we see some of these action as disrespect to his and our work. Its not only **You cant see me block.** Its more blocks and items. its basicly all block variants e.g **stargate base block (variant)** and we still continue in this tradition...

2023-11-29 19:13 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +prop.jsg.platform_ships_block.name=Ship Ring Platform
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:13 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.dhd_block.name=Milky Way Dial Home Device
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:13 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.dhd_pegasus_block.name=Pegasus Dial Home Device
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:13 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_milkyway_chevron_block.name=Milky Way Stargate Chevron
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:13 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_orlin_member_block.name=Orlin's Stargate Ring
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:14 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_universe_ring_block.name=Universe Stargate Ring
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:14 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_pegasus_chevron_block.name=Pegasus Stargate Chevron
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:14 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.capacitor_block_empty.name=Empty Capacitor Bank
I already explained to you that this is not a matter of opinion, but a matter of the item names being grammatically correct in the English language. Others have agreed with me that my revision to item names such as these is better than what they were before.

2023-11-29 19:15 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> -tile.jsg.invisible_block.name=You can't see me block
This is, frankly, the most rediculous thing that I have ever read on GitHub.

2023-11-29 19:15 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +prop.jsg.platform_ships_block.name=Ship Ring Platform
See above comments regarding naming scheme.

2023-11-29 19:16 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> -tile.jsg.dhd_block.name=Dial Home Device (Milky Way DHD)
You are being unneededly hostile. You can literally just type "dial" and find the DHD in JEI instantly.

2023-11-29 19:17 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> -tile.jsg.dhd_pegasus_block.name=Dial Home Device (Pegasus DHD)
Again, it is just as easily reachable in JEI by searching for "dial"

2023-11-29 19:17 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.stargate_orlin_base_block.name=Orlin's Stargate Base
You could just search for "orlin" in JEI to find it. Its not a problem.

2023-11-29 19:18 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
see previous reply.

2023-11-29 19:18 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +death.attack.wrongSide=%s entered the wrong side of the gate
What is this even supposed to mean?

2023-11-29 19:19 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.creative_zpm.name=Creative Zero Point Module (ZPM)
What's the issue?

2023-11-29 19:19 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +jsg.subtitle.iris_hit=Thud against the iris
You dont even speak English as your native language...

2023-11-29 19:19 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +jsg.subtitle.shield_hit=Thud against the shield
See previous reply.

2023-11-29 19:31 UTC, Renno231 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.creative_zpm.name=Creative Zero Point Module (ZPM)
This seems like a valid change

2023-11-29 19:31 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.gear_naquadah.name=Naquadah Gear
All of these revised names are just as searchable as the originals. You dont need to type the full word into JEI to find it, and you can search for two keywords at once with a space.

2023-11-29 19:35 UTC, Renno231 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +tile.jsg.transportrings_controller_block.not_linked=Controller is not linked
It does read better as Transport Ring Controller. Yes, there are multiple transport rings, but the Controller controls each individual ring in parallel, hence Ring Controller (not Rings). Also, from a technical aspect, I don't think it's necessarily required that there are multiple rings in a transporter as each ring seems to only add to the volume of space transported (sufficient enough to transport humans and objects of comparable size in the show)

2023-11-29 19:39 UTC, Renno231 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +config.jsg.zpm.tooltip=Configuration of ZPMs and ZPM Hubs
There's technically two types of ZPM (normal and creative) so it should be ZPMs from that alone, but it would also be clearer since there is the potential for there to be more than 1 ZPM in a given world file.

2023-11-29 19:44 UTC, Renno231 commented on src/main/resources/assets/jsg/lang/en_us.lang
> +death.attack.wrongSide=%s entered the wrong side of the gate
I'm not sure what this response means but the cremation messages are something of a meme at this point so I could see the reason for keeping them, though it would be nice to see this optionally changed in a config if possible. The wrongSide message change is valid

2023-11-29 19:52 UTC, VirgilCore commented on src/main/resources/assets/jsg/lang/en_us.lang
> +item.jsg.universe_dialer.broken.name=Broken Universe Dialer
If it's not in the mod anymore, I might as well remove this line.

2023-11-29 21:33 UTC, closed without merging

2023-11-29 21:33 UTC, MineDragonCZ commented
Stopped working on it and blocked from org for policy reasons